version: "3.1"

services:
  server:
    build: .
    ports:
      - "6111:6111"
      - "6112:6112"

  mysql:
    image: "mysql:8.3.0"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
